name: axi
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.2.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  fractal:
    path: ../fractal
  signed_fractal:
    path: ../signed_fractal
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0